CC = gcc
LIB = -lsocket -lnsl

all: server client myftpshare

server: server.c
        ${CC} -o server server.c ${LIB}

client: client.c
	${CC} -o client client.c ${LIB}

myftpshare: myftpshare.c
	${CC} -o myftpshare myftpshare.c ${LIB}

clean:
	rm server
	rm client	
        rm myftpshare