CC = gcc
LIB = -lsocket -lnsl -pthread

all: myftpserver myftpclient myftp

myftpserver: myftpserver.c
        ${CC} -o myftpserver myftpserver.c ${LIB}

myftpclient: myftpclient.c
	${CC} -o myftpclient myftpclient.c ${LIB}

myftp: myftp.c
	${CC} -o myftp myftp.c ${LIB}

clean:
	rm myftpserver
	rm myftpclient	
        rm myftp