CC = gcc
LIB = -pthread

all: myftp myftpserver myftpclient 

myftp: myftp.c
	${CC} -c myftp.c ${LIB}
	

myftpserver: myftpserver.c
	${CC} -c myftpserver.c ${LIB}
	${CC} -o myftpserver myftp.o myftpserver.o ${LIB}

myftpclient: myftpclient.c
	${CC} -c myftpclient.c ${LIB}
	${CC} -o myftpclient myftp.o myftpclient.o ${LIB}



clean:
	rm myftpserver
	rm myftpclient
	rm myftp.o
	rm myftpserver.o
	rm myftpclient.o		
