CC = gcc
LIB =

all: myftpshare server client 

myftpshare: myftpshare.c
	${CC} -c myftpshare.c ${LIB}
	

server: server.c
	${CC} -c server.c ${LIB}
	${CC} -o server myftpshare.o server.o ${LIB}

client: client.c
	${CC} -c client.c ${LIB}
	${CC} -o client myftpshare.o client.o ${LIB}



clean:
	rm server
	rm client
	rm myftpshare.o
	rm server.o
	rm client.o		
